db.restaurants.find()
db.restaurants.find({}, {"restaurant_id": 1, "name": 1, "borough": 1, "cuisine": 1})
db.restaurants.find({}, {"_id": 0, "restaurant_id": 1, "name": 1, "borough": 1, "cuisine": 1})
db.restaurants.find({}, {"_id": 0, "restaurant_id": 1, "name": 1, "borough": 1, "address.zipcode":1})
db.restaurants.find({"borough": "Bronx"})
db.restaurants.find({"borough": "Bronx"}).limit(5)
db.restaurants.find().skip(5).limit(5)
db.restaurants.find({"grades": {$elemMatch:{"score":{$gt:90}}}})
db.restaurants.find({"grades": {$elemMatch:{"score":{$gt:80, $lt:100}}}})
db.restaurants.find({"address.coord.0": {$lt: -95.754168}})
db.restaurants.find({"cuisine": {$not: {$eq: "American "}}, "grades": {$elemMatch: {"score": {$gt:70}}}, "address.coord.0": {$lt:-65.754168}})
db.restaurants.find({"cuisine": {$ne: "American "}, "grades.score": {$gt: 70}, "address.coord.0": {$lt: -65.854168}})
db.restaurants.find({"cuisine": {$ne: "American "}, "grades.grade": "A", "borough": {$ne: "Brooklyn"}}).sort({"cuisine": -1})
db.restaurants.find({"name": /^Wil/}, {"_id":0, "restaurants_id":1, "name":1, "borough":1, "cuisine":1})
db.restaurants.find({"name": /ces$/}, {"_id":0, "restaurants_id":1, "name":1, "borough":1, "cuisine":1})
db.restaurants.find({"name": /Reg/}, {"_id":0, "restaurants_id":1, "name":1, "borough":1, "cuisine":1})
db.restaurants.find({"borough": "Bronx", $or:[{"cuisine": "American "},{"cuisine": "Chinese"}]})
db.restaurants.find({$or:[{"borough": "Staten Island"},{"borough": "Queens"},{"borough": "Bronx"},{"borough": "Brooklyn"}]}, {"_id":0, "restaurant_id":1, "name":1, "borough":1, "cuisine":1})
db.restaurants.find({"borough": {$nin: ["Staten Island", "Queens", "Bronx", "Brooklyn"]}}, {"_id":0, "restaurant_id":1, "name":1, "borough":1, "cuisine":1})
db.restaurants.find({"grades": {$elemMatch: {"score":{$lt: 10}}}}, {"_id":0, "restaurant_id":1, "name":1, "borough":1, "cuisine":1})
db.restaurants.find({$and: [{"cuisine": "Seafood"}, {$or: [{"cuisine": {$nin: ["American ", "Chinese"]}}, {"name": /^Wil/}]}]}, {"_id":0, "restaurant_id":1, "name":1, "borough":1, "cuisine":1})
db.restaurants.find({"grades": {$elemMatch: {"grade": "A", "score": 11, "date": ISODate("2014-08-11T00:00:00Z")}}}, {"_id":0, "restaurant_id":1, "name":1, "grades":1})
db.restaurants.find({"grades.1.grade": "A", "grades.1.score": 9, "grades.1.date": ISODate("2014-08-11T00:00:00Z")}, {"_id":0, "restaurant_id":1, "name":1, "grades":1})
db.restaurants.find({$and: [{"address.coord.1": {$gt: 42}}, {"address.coord.1": {$lt: 52}}]}, {"_id":0, "restaurant_id":1, "name":1, "address.street":1, "address.coord":1})
db.restaurants.find().sort({"name": 1})
db.restaurants.find().sort({"name": -1})
db.restaurants.find().sort({"cuisine": 1}, {"borough": -1})
db.restaurants.find({"address.street": {$ne: null}})
db.restaurants.find({$and: [{"address.coord.0": {$type: "double"}}, {"address.coord.1": {$type: "double"}}]})
db.restaurants.find({"grades": {$elemMatch: {"score": {$mod: [7,0]}}}}, {"_id":0, "restaurant_id":1, "name":1, "grades":1})
db.restaurants.find({"name": /mon/}, {"_id":0, "name":1, "borough":1, "address.coord":1, "cuisine":1})
db.restaurants.find({"name": /^Mad/}, {"_id":0, "name":1, "borough":1, "address.coord":1, "cuisine":1})